[build]
  command = "npm run build"
  publish = "dist/Portafolio-Personal/browser"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
